### ISSUE TITLE
Error during WebSocket handshake

### ISSUE THREAD

**Issue by SilvijaBart** [XSockets/XSockets.Clients#18]
Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received. It only happens on Chrome.

**Comment by uffebjorklund** [comment]
@SilvijaBart 
 - What server version are you using?
 - What client version are you using?

If possible provide some sample code

From your description it sounds like you are using a WebSocket-Server that is not XSockets?
The XSockets client will send a websocket sub-protocol `XSockets.NET`. If the server does not respond with the same sub-protocol in the `Sec-WebSocket-Protocol` chrome will deny the connection.
