### ISSUE TITLE
Any examples with .Net Core

### ISSUE THREAD

**Issue by DavidKCalnex** [XSockets/XSockets.Clients#21]
Is there any exmaple someone could put together with this working with .Net Core. The libs themselves import but I get null back when I try the following:

`XSockets.Plugin.Framework.Composable.GetExport<IXSocketServerContainer>();
`

Any help at all would be much appreciated!

**Comment by uffebjorklund** [comment]
@DavidKCalnex Created a small sample here... https://github.com/uffebjorklund/XSockets.dotnetcore.sample
But basiccally all you need is the preview package `<PackageReference Include="XSockets.Server" Version="5.8.0-preview001" />` since the others doe snot support dotnet core.
```
using System;
using XSockets.Core.Common.Socket;
using XSockets.Plugin.Framework;

namespace SampleServer
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var container = Composable.GetExport<IXSocketServerContainer>())
            {
                container.Start();
                Console.ReadLine();
            }
        }
    }
}

```

**Comment by DavidKCalnex** [comment]
Wow what a response!

That'll do thank you very much sir!

David
